### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by JOduMonT** [gonapps/hugo-apps-theme#1]
With the name, I was hoping something with a service worker and or at least a manifest
but neither are integrated.
it is planned in a near future ??

**Comment by binkoni** [comment]
Thanks I haven't thought about PWAs, I'll try to work on that as soon as possible.

**Comment by binkoni** [comment]
But can you elaborate more on the integration part?
I tried this example PWA to my theme:
https://github.com/ryanwhocodes/template-progressive-web-app
But just adding entire 'public' directory into content directory seems to work fine.

**Comment by JOduMonT** [comment]
>  I tried this example PWA to my theme:
Sorry french is my mother tongue so I might not understand properly, ... but;
do you means you add this repo on top of hugo-apps-theme and it works offline ?

My test for your theme was with [lighthouse](https://developers.google.com/web/tools/lighthouse/)

I also must admit I'm not an expert of all these techno (PWA, service workers, hugo)

**Comment by binkoni** [comment]
Before v1.2.2, due to a bug, HTML head element is not rendered. Because of that resources like manifest.json is also not loaded.
From v1.2.2 This bug is fixed, I also tested PWA example with lighthouse and the test was successful.
